# Generated by Django 4.2.6 on 2024-10-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('facility', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(blank=True, default=True, null=True)),
                ('max_booking_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hourly_cost_assisted', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hourly_cost_external', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hourly_cost_external_assisted', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hourly_cost_buyer', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hourly_cost_buyer_assisted', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('booked_start_date', models.DateTimeField()),
                ('booked_end_date', models.DateTimeField()),
                ('is_assisted', models.BooleanField(blank=True, default=True, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('machine_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalendarApp.machine')),
            ],
        ),
    ]
