# Generated by Django 4.2.6 on 2023-12-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CalendarApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="hourly_cost_buyer_assisted",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
