# Generated by Django 4.2.6 on 2024-01-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CalendarApp", "0002_machine_hourly_cost_buyer_assisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="max_booking_duration",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
