# Generated by Django 4.2.6 on 2024-01-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CalendarApp", "0003_machine_max_booking_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="hourly_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="hourly_cost_assisted",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="hourly_cost_external",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="hourly_cost_external_assisted",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
