# Generated by Django 4.2.6 on 2023-12-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CalendarApp", "0001_initial"),
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="machines4ThisUser",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="machines4ThisUser",
                to="CalendarApp.machine",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="machines_bought",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="machines_bought",
                to="CalendarApp.machine",
            ),
        ),
    ]
