# Generated by Django 4.2.6 on 2023-12-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CalendarApp", "0001_initial"),
        ("UserApp", "0003_alter_userprofile_machines4thisuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="group_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="machines_bought",
        ),
        migrations.CreateModel(
            name="MBCGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MBC1", "MBC1"),
                            ("MBC2", "MBC2"),
                            ("NO_MBC", "NO MBC"),
                        ],
                        default="NO_MBC",
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "machines_bought",
                    models.ManyToManyField(
                        blank=True,
                        related_name="machines_bought",
                        to="CalendarApp.machine",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UserApp.mbcgroup",
            ),
        ),
    ]
