# Generated by Django 4.2.6 on 2023-12-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserApp", "0004_remove_userprofile_group_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mbcgroup",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[("MBC1", "MBC1"), ("MBC2", "MBC2"), ("NO_MBC", "NO_MBC")],
                default="NO_MBC",
                max_length=6,
                null=True,
            ),
        ),
    ]
