# Generated by Django 4.2.6 on 2024-10-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0005_alter_booking_machine_obj_alter_machine_hourly_cost_and_more'),
        ('UserApp', '0006_userprofile_password_reset_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MBCGroup',
            new_name='Group',
        ),
    ]
